### ISSUE TITLE
Error publishing Garbanzo API

### ISSUE THREAD

**Issue by stuppie** [WebsmartAPI/smartAPI#5]
Steps to reproduce:

- Go to: http://smart-api.info/editor/#/
- File -> Paste JSON
- Paste in value from http://garbanzo.sulab.org/swagger_smartapi.json (It says "✔ Valid Swagger")
- Hit "Publish"

I get a popup with the following error: 

> Error"<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>"

The swagger.json file is being auto-generated with [flask_restplus](http://flask-restplus.readthedocs.io/en/stable/swagger.html). It validates upon import into the editor, and confirmed validation using an [external tool](http://bigstickcarpet.com/swagger-parser/www/index.html) as well.

**Comment by twhetzel** [comment]
@stuppie what value are you pasting in from http://garbanzo.sulab.org/swagger_smartapi.json?

**Comment by stuppie** [comment]
Sorry I meant paste in the entire page.

**Comment by stuppie** [comment]
Its still not parsing it correctly. When you look at the page in the swagger editor ([link](http://smart-api.info/editor/#/?import=http://smart-api.info/api/metadata/R2FyYmFuem8gQVBJfDEuMC4xMTN8R3JlZyBTdHVwcA==)) its missing all of the parameters.
