### ISSUE TITLE
Use tag "production" to label the latest API entry in the registry

### ISSUE THREAD

**Issue by newgene** [WebsmartAPI/smartAPI#7]
smartAPI registry currently save all versions of user-submitted API metadata. While it's nice to have the versioned historical records, they clutters the registry display. I suggest to add a "production" tag to label the latest API entry for each API, and the API registry will by default display the "production"-tagged entries only:

```
tags:
  - name: production
    description: This is the latest API metadata
```

**Comment by micheldumontier** [comment]
where will the production tag be stored? in the metadata document? that won't work because previous versions will have them...

**Comment by newgene** [comment]
I was thinking of storing in the metadata document, using the existing "tags" field. Users will have to handle the add/remove of this tag.

**Comment by stuppie** [comment]
If the version is stored using semantic versioning you can just use the latest version

**Comment by micheldumontier** [comment]
but we know that people may have 2 concurrently supported APIs. so just looking at the latest tag isn't sufficient.

**Comment by micheldumontier** [comment]
We really need a user management system + ability to modify the "production" metadata for the repository.

**Comment by newgene** [comment]
Agreed. Closing this issue for now. As we are adding user authentication, this issue should be solved without the need of using tags.
